# Generated by Django 5.2.1 on 2025-05-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='status',
            field=models.CharField(default='C', max_length=1),
        ),
    ]
