# Generated by Django 5.2.1 on 2025-05-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_itemvenda_quantidade_alter_produto_vendedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('C', 'Concluído')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='status',
            field=models.CharField(choices=[('C', 'Consumidor'), ('V', 'Vendedor')], default='C', max_length=1),
        ),
    ]
