# Generated by Django 5.2.1 on 2025-05-15 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_pagamento_status_alter_perfil_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='user',
        ),
    ]
